version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
  backend:
    build:
      context: ./apps/backend
    command: npm run dev
    working_dir: /app
    environment:
      - MONGO_URI=mongodb://mongo:27017/aura
      - CLIENT_ORIGIN=http://localhost:3000
    ports:
      - '4000:4000'
    volumes:
      - ./apps/backend:/app
    depends_on:
      - mongo
      - redis
  frontend:
    build:
      context: ./apps/frontend
    command: npm run dev
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    volumes:
      - ./apps/frontend:/app
    depends_on:
      - backend
volumes:
  mongo-data:


